steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_IMAGE}"
      - "-f"
      - "backend/Dockerfile"
      - "backend"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_IMAGE}"
images:
  - "${_IMAGE}"
substitutions:
  _IMAGE: "us-central1-docker.pkg.dev/animathic-backend/cloud-run-source-deploy/animathic-backend:latest"
