# Cloud Build configuration for Animathic Backend
# This file enables automated builds and deployments

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'build', '--platform', 'linux/amd64', '-f', 'Dockerfile.production', '-t', 'gcr.io/$PROJECT_ID/animathic-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/animathic-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'animathic-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/animathic-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--port'
      - '8080'
      - '--execution-environment'
      - 'gen2'
      - '--cpu-boost'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,LOG_LEVEL=INFO'
      - '--set-secrets'
      - 'GOOGLE_AI_API_KEY=GOOGLE_AI_API_KEY:latest,SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_ANON_KEY=SUPABASE_ANON_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/animathic-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
