name: CI (dev llm)

on:
  pull_request:
    branches: [ development/llm-upgrade ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements_minimal.txt
          pip install pytest
      - name: Run tests
        run: |
          cd backend
          PYTHONPATH=. pytest -q

